#!/bin/bash

# for automatic compiling

if [ -L $0 ] ; then
  DIR=$(dirname $(readlink -f $0)) ;
else
  DIR=$(dirname $0) ;
fi
cd $DIR

git pull

grep -r --exclude='TODO' --exclude='work' "TODO" * > TODO
wc -l TODO
echo

tmux new-session -d -s texNum
tmux new-window -t texNum:2 -n 'latexmk' 'latexmk -pvc -pdf document.tex'
tmux new-window -t texNum:3 -n 'log' 'vim document.log'
tmux select-window -t texNum:1
tmux attach-session -t texNum

#git commit -a -m "automatic commit"
git commit -a
git push
